// <auto-generated />
namespace SeminarskiRad.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class init_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201704052055083_init_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
